included:
  - WaiterRobot

file_length:
  warning: 500
  error: 1200

line_length:
  warning: 200
  error: 300  

function_body_length:
  warning: 150
  error: 250

force_cast:
  severity: warning

force_try:
  severity: error

cyclomatic_complexity:
  ignores_case_statements: true
  
trailing_comma:
  mandatory_comma: true

