name: WaiterRobot

fileGroups:
  - .gitignore
  - README.md
  - project.yml

packages:
  shared:
    url: https://github.com/DatepollSystems/waiterrobot-mobile_android-shared.git
    version: 0.1.10
  UIPilot:
    url: https://github.com/canopas/UIPilot.git
    from: 1.3.1
  CodeScanner:
    url: https://github.com/twostraws/CodeScanner
    from: 2.2.1

targetTemplates:
  WaiterRobot:
    type: application
    platform: iOS
    sources:
      - path: "WaiterRobot"
      - path: "TargetSpecificResources/${target_name}"
        group: "WaiterRobot/Resources"
        
    dependencies:
      - package: shared
      - package: UIPilot
      - package: CodeScanner
    
    info:
      path: ".generated/${target_name}.plist"
      properties:
        CFBundleShortVersionString: "2.0.1"
        CFBundleVersion: "20001"
        API_BASE: "${apiBase}"

        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleDisplayName: "${displayName}"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "${identifier}"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleLocalizations:
          - en
          - de
        CFBundleName: "${target_name}"
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        ITSAppUsesNonExemptEncryption: false
        LSRequiresIPhoneOS: true
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        NSCameraUsageDescription: "Camera is needed to scan QR-Codes"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchStoryboardName: "LaunchScreen"
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          
    entitlements:
      path: ".generated/${target_name}.entitlements"
      properties:
        com.apple.developer.associated-domains:
          - "applinks:${deeplinkDomain}"
        
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "${identifier}"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        INFOPLIST_FILE: ".generated/${target_name}.plist"
        CODE_SIGN_STYLE: "Automatic"
        CODE_SIGN_ENTITLEMENTS: ".generated/${target_name}.entitlements"
        DEVELOPMENT_TEAM: "28TM58T3GZ"
        PRODUCT_NAME: "${displayName}"
        ENABLE_PREVIEWS: "YES"
      configs:
        RELEASE:
          ONLY_ACTIVE_ARCH: "NO"
        DEBUG:
          ONLY_ACTIVE_ARCH: "YES"

targets:
  WaiterRobot:
    templates:
      - WaiterRobot
    templateAttributes:
      identifier: "org.datepollsystems.waiterrobot"
      displayName: "WaiterRobot"
      deeplinkDomain: "my.kellner.team"
      apiBase: "https://my.kellner.team/api"
  
  WaiterRobotLava:
    templates:
      - WaiterRobot
    templateAttributes:
      identifier: "org.datepollsystems.waiterrobot.beta"
      displayName: "WaiterRobot Lava"
      deeplinkDomain: "lava.kellner.team"
      apiBase: "https://lava.kellner.team/api"
  
