name: WaiterRobot

fileGroups:
  - .gitignore
  - README.md
  - project.yml

packages:
  shared:
    url: https://github.com/DatepollSystems/waiterrobot-mobile_android-shared.git
    version: 0.1.9
  UIPilot:
    url: https://github.com/canopas/UIPilot.git
    from: 1.3.1
  CodeScanner:
    url: https://github.com/twostraws/CodeScanner
    from: 2.2.1

targets:
  WaiterRobot:
    type: application
    platform: iOS
    sources:
      - path: "WaiterRobot"

    scheme:
      testTargets:
        - "WaiterRobotTests"
        - "WaiterRobotUITests"
        
    dependencies:
      - package: shared
      - package: UIPilot
      - package: CodeScanner
        
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "org.datepollsystems.waiterrobot"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        INFOPLIST_FILE: "WaiterRobot/SupportingFiles/Info.plist"
        CODE_SIGN_STYLE: "Automatic"
        CODE_SIGN_ENTITLEMENTS: "WaiterRobot/SupportingFiles/WaiterRobot.entitlements"
        DEVELOPMENT_TEAM: "28TM58T3GZ"
        PRODUCT_NAME: "$(TARGET_NAME)"
        ENABLE_PREVIEWS: "YES"
      configs:
        RELEASE:
          ONLY_ACTIVE_ARCH: "NO"
        DEBUG:
          ONLY_ACTIVE_ARCH: "YES"

  WaiterRobotTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: "WaiterRobotTests"
    dependencies:
      - target: "WaiterRobot"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "org.datepollsystems.waiterrobot.WaiterRobotTests"
        GENERATE_INFOPLIST_FILE: "YES"
        IPHONEOS_DEPLOYMENT_TARGET: "15.5"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: "Automatic"
        DEVELOPMENT_TEAM: "28TM58T3GZ"

  WaiterRobotUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: "WaiterRobotUITests"
    dependencies:
      - target: "WaiterRobot"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "org.datepollsystems.waiterrobot.WaiterRobotUITests"
        GENERATE_INFOPLIST_FILE: "YES"
        IPHONEOS_DEPLOYMENT_TARGET: "15.5"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: "Automatic"
        DEVELOPMENT_TEAM: "28TM58T3GZ"
