name: WaiterRobot

fileGroups:
  - .gitignore
  - README.md
  - project.yml
  - fastlane
  - Gemfile
  - .github/workflows

packages:
  shared:
    url: https://github.com/DatepollSystems/waiterrobot-mobile_android-shared.git
    version: "1.0.2-lava-1676624683"
  UIPilot:
    url: https://github.com/canopas/UIPilot.git
    from: 1.3.1
  CodeScanner:
    url: https://github.com/twostraws/CodeScanner
    from: 2.2.1

targetTemplates:
  WaiterRobot:
    type: application
    platform: iOS
    sources:
      - path: "WaiterRobot"
      - path: "TargetSpecificResources/${target_name}"
        group: "WaiterRobot/Resources"
        
    dependencies:
      - package: shared
      - package: UIPilot
      - package: CodeScanner
    
    info:
      path: ".generated/${target_name}.plist"
      properties:
        CFBundleShortVersionString: "2.0.2"
        # Generate VersionCode from VersionName (major * 10_000 + minor * 100 + patch, e.g. 1.2.3 -> 10203, 1.23.45 -> 12345)
        # Only used for prod releases. Lava uses epochMinute (same as on Android)
        CFBundleVersion: "20002"

        API_BASE: "${apiBase}"
        VERSION_SUFFIX: "${versionSuffix}"

        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleDisplayName: "${displayName}"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "${identifier}"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleLocalizations:
          - en
          - de
        CFBundleName: "${target_name}"
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        ITSAppUsesNonExemptEncryption: false
        LSRequiresIPhoneOS: true
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        NSCameraUsageDescription: "Camera is needed to scan QR-Codes"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchStoryboardName: "LaunchScreen"
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          
    entitlements:
      path: ".generated/${target_name}.entitlements"
      properties:
        com.apple.developer.associated-domains:
          - "applinks:${deeplinkDomain}"
        
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "${identifier}"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        INFOPLIST_FILE: ".generated/${target_name}.plist"
        CODE_SIGN_STYLE: "Manual"
        CODE_SIGN_ENTITLEMENTS: ".generated/${target_name}.entitlements"
        DEVELOPMENT_TEAM: "28TM58T3GZ"
        PRODUCT_NAME: "${displayName}"
        ENABLE_PREVIEWS: "YES"
      configs:
        RELEASE:
          ONLY_ACTIVE_ARCH: "NO"
          PROVISIONING_PROFILE_SPECIFIER: "match AppStore ${identifier}"
          CODE_SIGN_IDENTITY: "iPhone Distribution"
        DEBUG:
          ONLY_ACTIVE_ARCH: "YES"
          PROVISIONING_PROFILE_SPECIFIER: "match Development ${identifier}"
          CODE_SIGN_IDENTITY: "iPhone Developer"

targets:
  WaiterRobot:
    templates:
      - WaiterRobot
    scheme: {}
    templateAttributes:
      identifier: "org.datepollsystems.waiterrobot"
      displayName: "WaiterRobot"
      deeplinkDomain: "my.kellner.team"
      apiBase: "https://my.kellner.team/api"
      versionSuffix: ""
  
  WaiterRobotLava:
    templates:
      - WaiterRobot
    scheme: {}
    templateAttributes:
      identifier: "org.datepollsystems.waiterrobot.beta"
      displayName: "WaiterRobot Lava"
      deeplinkDomain: "lava.kellner.team"
      apiBase: "https://lava.kellner.team/api"
      versionSuffix: "lava"
    preBuildScripts:
      - name: Set BuildNumber to epochMinute
        basedOnDependencyAnalysis: false # run for each build
        script: |
                # Lava uses the epochMinute as buildNumber
                /usr/libexec/PlistBuddy -c "Set CFBundleVersion $(($(date +"%s")/60))" ".generated/WaiterRobotLava.plist"
  
