default_platform(:ios)

platform :ios do
    before_all do
        xcodes(version: "16.1", select_for_current_build_only: true)
    end

    desc "Run all iOS unit and ui tests."
    lane :test do
        run_tests(scheme: "WaiterRobotLava")
    end
    
    desc "Send a notification to Slack"
    lane :sendSlackMessage do |options|
      ensure_env_vars(
        env_vars: ["SLACK_WEBHOOK_URL"]
      )
      
      slack_webhook_url = ENV['SLACK_WEBHOOK_URL']
      version = options[:version]
      environment = options[:env]

      json_body = <<-JSON
        {
          "blocks": [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": "🚀 New iOS #{environment} version available on TestFlight",
                "emoji": true
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Version:* `#{version}`"
              }
            },
          ]
        }
      JSON

      sh <<-EOS
        curl -X POST \
         --header 'Content-type: application/json' \
         --url "#{slack_webhook_url}" \
         --data '#{json_body}'
      EOS
    end
end
