name: Publish to TestFlight
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'project.yml'
      - 'WaiterRobot/**'
      - 'TargetSpecificResources/**'
      - '.github/workflows/publish.yml'
      - 'fastlane/**'
      - 'Gemfile'
      - 'Gemfile.lock'

jobs:    
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
          
      - name: Setup Ruby 3.2.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'
          bundler-cache: true
      
      - name: Netrc api.github.com
        uses: extractions/netrc@v1
        with:
          machine: maven.pkg.github.com
          username: ${{ secrets.NETRC_USERNAME }}
          password: ${{ secrets.NETRC_TOKEN }}
          
      - name: Setup xcodegen and init xcode project
        uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          use-cache: true
      
      - name: Run tests with fastlane
        run: bundle exec fastlane test
        
      - name: Extract secrets
        run: |
          cd fastlane
          echo "${{ secrets.KEYS_TAR_ASC }}" > .keys.tar.gz.asc
          gpg -d --passphrase "${{ secrets.KEYS_PASSPHRASE }}" --batch .keys.tar.gz.asc > .keys.tar.gz
          tar xzf .keys.tar.gz
          chmod 600 .keys/github-deploy-key
          cd ..

      - name: Publish to TestFlight
        run: bundle exec fastlane releaseWaiterRobot_${{ github.ref_name }}
        env:
          FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
          FASTLANE_CERTIFICATES_GIT_URL: ${{ secrets.FASTLANE_CERTIFICATES_GIT_URL }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
