name: SwiftFormat

on:
  pull_request:
    paths:
      - '.github/workflows/swiftformat.yml'
      - '.swiftformat'
      - '**/*.swift'

jobs:
  format:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SwiftFormat
      run: brew install swiftformat
    - name: Run SwiftFormat
      run: swiftformat . --lint
