name: SwiftFormat

on:
  pull_request:
    paths:
      - '.github/workflows/swiftformat.yml'
      - '.swiftformat'
      - '**/*.swift'

jobs:
  format:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Run SwiftFormat
      run: swift run swiftformat . --lint
