name: Refresh certificates
on:
  workflow_dispatch:
  push:

jobs:    
  sync-certs:
    runs-on: macos-13
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
          
      - name: Setup Ruby 3.3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true
      
      - name: Netrc maven.pkg.github.com
        uses: extractions/netrc@v1
        with:
          machine: maven.pkg.github.com
          username: cirunner
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Run XcodeGen
        run: xcodegen

      - name: Install xcodes
        run: brew install xcodes
        
      - name: Extract secrets
        run: |
          cd fastlane
          echo "${{ secrets.KEYS_TAR_ASC }}" > .keys.tar.gz.asc
          gpg -d --passphrase "${{ secrets.KEYS_PASSPHRASE }}" --batch .keys.tar.gz.asc > .keys.tar.gz
          tar xzf .keys.tar.gz
          chmod 600 .keys/github-deploy-key
          cd ..
      
      - name: Fastlane sync certificates
        run: bundle exec fastlane sync_certificates
        env:
          FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
          FASTLANE_CERTIFICATES_GIT_URL: ${{ secrets.FASTLANE_CERTIFICATES_GIT_URL }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

