name: Publish to TestFlight
concurrency: # Cancel currently running releases when a new one is started
  group: publish-android-${{ github.ref_name }}
  cancel-in-progress: true
on:
  workflow_dispatch:

jobs:    
  publish:
    runs-on: macos-13
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
          
      - name: Setup Ruby 3.3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true
      
      - name: Netrc maven.pkg.github.com
        uses: extractions/netrc@v1
        with:
          machine: maven.pkg.github.com
          username: cirunner
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Run XcodeGen
        run: xcodegen

      - name: Install xcodes
        run: brew install xcodes

      - name: Run tests with fastlane
        run: bundle exec fastlane test
        
      - name: Extract secrets
        run: |
          cd fastlane
          echo "${{ secrets.KEYS_TAR_ASC }}" > .keys.tar.gz.asc
          gpg -d --passphrase "${{ secrets.KEYS_PASSPHRASE }}" --batch .keys.tar.gz.asc > .keys.tar.gz
          tar xzf .keys.tar.gz
          chmod 600 .keys/github-deploy-key
          cd ..
      
      - name: Fastlane sync certificates
        run: bundle exec fastlane sync_certificates

