name: Run unit and ui tests

on:
  push:
    branches-ignore:
      - 'develop'
      - 'main'
  
jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Ruby 3.3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - name: Netrc api.github.com
        uses: extractions/netrc@v2
        with:
          machine: maven.pkg.github.com
          username: cirunner
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install xcodes
        run: brew install xcodes

      - name: Run XcodeGen
        run: swift run xcodegen

      - name: Run tests with fastlane
        run: bundle exec fastlane test
