name: Run unit and ui tests

on:
  push:
  
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Ruby 3.1.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
    
      - name: Setup xcodegen and init xcode project
        uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          use-cache: true

      - name: Run tests with fastlane
        run: bundle exec fastlane test
